/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Datos;
import Formularios.frmUsuarios;

/**
 *
 * @author raulVe
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private Datos misDatos;

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;
    }
    
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuArchivoClientes = new javax.swing.JMenuItem();
        mnuArchivoProduc = new javax.swing.JMenuItem();
        mnuArchivoUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuArchivoCamClave = new javax.swing.JMenuItem();
        mnuArchivoCamUsua = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuArchivoSalir = new javax.swing.JMenuItem();
        mnuMovi = new javax.swing.JMenu();
        mnuMoviNFactura = new javax.swing.JMenuItem();
        mnuMoviRFactura = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuAyudaAcerca = new javax.swing.JMenuItem();
        mnuAyudaAyu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Facturación");

        dpnEscritorio.setBackground(new java.awt.Color(204, 204, 204));

        mnuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/office-material.png"))); // NOI18N
        mnuArchivo.setText("Archivo");

        mnuArchivoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cliente de empresa-32.png"))); // NOI18N
        mnuArchivoClientes.setText("Clientes");
        mnuArchivoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoClientesActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoClientes);

        mnuArchivoProduc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Producto-32.png"))); // NOI18N
        mnuArchivoProduc.setText("Productos");
        mnuArchivo.add(mnuArchivoProduc);

        mnuArchivoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario-32.png"))); // NOI18N
        mnuArchivoUsuario.setText("Usuarios");
        mnuArchivoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoUsuarioActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoUsuario);
        mnuArchivo.add(jSeparator1);

        mnuArchivoCamClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Olvidó su contraseña-32.png"))); // NOI18N
        mnuArchivoCamClave.setText("Cambio Clave");
        mnuArchivo.add(mnuArchivoCamClave);

        mnuArchivoCamUsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario-32 (1).png"))); // NOI18N
        mnuArchivoCamUsua.setText("Cambio Usuario");
        mnuArchivo.add(mnuArchivoCamUsua);
        mnuArchivo.add(jSeparator2);

        mnuArchivoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salida-32.png"))); // NOI18N
        mnuArchivoSalir.setText("Salir");
        mnuArchivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoSalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuArchivoSalir);

        jMenuBar1.add(mnuArchivo);

        mnuMovi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Factura-30.png"))); // NOI18N
        mnuMovi.setText("Movimientos");

        mnuMoviNFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Agregar archivo-30.png"))); // NOI18N
        mnuMoviNFactura.setText("Nueva Factura");
        mnuMovi.add(mnuMoviNFactura);

        mnuMoviRFactura.setText("Reporte Factura");
        mnuMovi.add(mnuMoviRFactura);

        jMenuBar1.add(mnuMovi);

        mnuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        mnuAyuda.setText("Ayuda");

        mnuAyudaAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acerca de-30.png"))); // NOI18N
        mnuAyudaAcerca.setText("Acerca de");
        mnuAyuda.add(mnuAyudaAcerca);

        mnuAyudaAyu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ayuda-30.png"))); // NOI18N
        mnuAyudaAyu.setText("Ayuda");
        mnuAyuda.add(mnuAyudaAyu);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuArchivoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoClientesActionPerformed

    }//GEN-LAST:event_mnuArchivoClientesActionPerformed

    private void mnuArchivoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoUsuarioActionPerformed
        frmUsuarios usuarioventa = new frmUsuarios();
        usuarioventa.setDatos(misDatos);
        dpnEscritorio.add(usuarioventa);
        usuarioventa.show();
        
    }//GEN-LAST:event_mnuArchivoUsuarioActionPerformed

    private void mnuArchivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuArchivoSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuArchivoCamClave;
    private javax.swing.JMenuItem mnuArchivoCamUsua;
    private javax.swing.JMenuItem mnuArchivoClientes;
    private javax.swing.JMenuItem mnuArchivoProduc;
    private javax.swing.JMenuItem mnuArchivoSalir;
    private javax.swing.JMenuItem mnuArchivoUsuario;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuAyudaAcerca;
    private javax.swing.JMenuItem mnuAyudaAyu;
    private javax.swing.JMenu mnuMovi;
    private javax.swing.JMenuItem mnuMoviNFactura;
    private javax.swing.JMenuItem mnuMoviRFactura;
    // End of variables declaration//GEN-END:variables
}
